package com.yazantarifi.models

enum class AndroidDebugEvent {
    SHOW_LAYOUT_BOUNDS,
    HIDE_LAYOUT_BOUNDS,
    ENABLE_DONT_KEEP_ACTIVITIES,
    DISABLE_DONT_KEEP_ACTIVITIES,
    SHOW_OVERDRAW_AREAS,
    HIDE_OVERDRAW_AREAS,
}