package com.yazantarifi.models

enum class AndroidDebugEvent {
    SHOW_LAYOUT_BOUNDS,
    HIDE_LAYOUT_BOUNDS,
    ENABLE_DONT_KEEP_ACTIVITIES,
    DISABLE_DONT_KEEP_ACTIVITIES,
    SHOW_OVERDRAW_AREAS,
    HIDE_OVERDRAW_AREAS,
    UN_INSTALL_APPLICATION,
    CLEAR_DATA_AND_RESTART_APPLICATION,
    CLEAR_DATA_APPLICATION,
    REMOVE_APPLICATION_PERMISSIONS,
    KILL_APPLICATION_ACTION,
    FOURCE_STOP_APPLICATION
}